/**
 * GENERATED by scripts/generate-automation-matrix.ts — do not edit by hand.
 * Regenerate with: npm run gen:matrix
 */
import { defineFeature } from "../../src/orchestrator/suite.js";
import { assert, assertEquals } from "../../src/orchestrator/context.js";
import { runConditionCase } from "./automationHarness.js";
import type { ConditionCase } from "../../src/domain/automationCatalog.js";

const CASES: unknown[] = [
  {
    "id": "automation.matrix.seed",
    "field": "-",
    "fieldType": "text",
    "operator": "(seed)",
    "valueClass": "match",
    "expected": "probe"
  },
  {
    "id": "automation.matrix.equals.text.match",
    "field": "subject",
    "fieldType": "text",
    "operator": "equals",
    "valueClass": "match",
    "expected": true,
    "conditionValue": "Refund",
    "ticketValue": "Refund"
  },
  {
    "id": "automation.matrix.equals.text.no_match",
    "field": "subject",
    "fieldType": "text",
    "operator": "equals",
    "valueClass": "no_match",
    "expected": false,
    "conditionValue": "Refund",
    "ticketValue": "Password reset instructions"
  },
  {
    "id": "automation.matrix.equals.text.null_value",
    "field": "subject",
    "fieldType": "text",
    "operator": "equals",
    "valueClass": "null_value",
    "expected": false,
    "conditionValue": "Refund",
    "ticketValue": "Password reset instructions"
  },
  {
    "id": "automation.matrix.equals.text.boundary",
    "field": "subject",
    "fieldType": "text",
    "operator": "equals",
    "valueClass": "boundary",
    "expected": false,
    "conditionValue": " Refund ",
    "ticketValue": "Refund"
  },
  {
    "id": "automation.matrix.equals.text.case_variant",
    "field": "subject",
    "fieldType": "text",
    "operator": "equals",
    "valueClass": "case_variant",
    "expected": false,
    "conditionValue": "REFUND",
    "caseSensitive": true,
    "ticketValue": "refund"
  },
  {
    "id": "automation.matrix.equals.select.match",
    "field": "priority",
    "fieldType": "select",
    "operator": "equals",
    "valueClass": "match",
    "expected": true,
    "conditionValue": "high",
    "ticketValue": "high"
  },
  {
    "id": "automation.matrix.equals.select.no_match",
    "field": "priority",
    "fieldType": "select",
    "operator": "equals",
    "valueClass": "no_match",
    "expected": false,
    "conditionValue": "urgent",
    "ticketValue": "low"
  },
  {
    "id": "automation.matrix.equals.select.null_value",
    "field": "priority",
    "fieldType": "select",
    "operator": "equals",
    "valueClass": "null_value",
    "expected": false,
    "conditionValue": "high"
  },
  {
    "id": "automation.matrix.equals.number.match",
    "field": "response_time",
    "fieldType": "number",
    "operator": "equals",
    "valueClass": "match",
    "expected": true,
    "ticketValue": 30,
    "conditionValue": 30
  },
  {
    "id": "automation.matrix.equals.number.no_match",
    "field": "response_time",
    "fieldType": "number",
    "operator": "equals",
    "valueClass": "no_match",
    "expected": false,
    "ticketValue": 30,
    "conditionValue": 999
  },
  {
    "id": "automation.matrix.equals.number.null_value",
    "field": "response_time",
    "fieldType": "number",
    "operator": "equals",
    "valueClass": "null_value",
    "expected": false,
    "conditionValue": 30
  },
  {
    "id": "automation.matrix.equals.number.boundary",
    "field": "response_time",
    "fieldType": "number",
    "operator": "equals",
    "valueClass": "boundary",
    "expected": true,
    "ticketValue": 30,
    "conditionValue": 30
  },
  {
    "id": "automation.matrix.equals.date.match",
    "field": "created_at",
    "fieldType": "date",
    "operator": "equals",
    "valueClass": "match",
    "expected": true,
    "ticketValue": "2026-09-21T06:33:03.224Z",
    "conditionValue": "2026-09-21T06:33:03.224Z"
  },
  {
    "id": "automation.matrix.equals.date.no_match",
    "field": "created_at",
    "fieldType": "date",
    "operator": "equals",
    "valueClass": "no_match",
    "expected": false,
    "ticketValue": "2026-09-21T06:33:03.225Z",
    "conditionValue": "2026-08-27T06:33:03.225Z"
  },
  {
    "id": "automation.matrix.equals.date.null_value",
    "field": "created_at",
    "fieldType": "date",
    "operator": "equals",
    "valueClass": "null_value",
    "expected": false,
    "conditionValue": "2026-09-21T06:33:03.225Z"
  },
  {
    "id": "automation.matrix.equals.date.boundary",
    "field": "created_at",
    "fieldType": "date",
    "operator": "equals",
    "valueClass": "boundary",
    "expected": true,
    "ticketValue": "2026-09-21T06:33:03.225Z",
    "conditionValue": "2026-09-21T06:33:03.225Z"
  },
  {
    "id": "automation.matrix.equals.boolean.match",
    "field": "is_urgent",
    "fieldType": "boolean",
    "operator": "equals",
    "valueClass": "match",
    "expected": true,
    "conditionValue": true,
    "ticketValue": true
  },
  {
    "id": "automation.matrix.equals.boolean.no_match",
    "field": "is_urgent",
    "fieldType": "boolean",
    "operator": "equals",
    "valueClass": "no_match",
    "expected": false,
    "conditionValue": true,
    "ticketValue": false
  },
  {
    "id": "automation.matrix.not_equals.text.match",
    "field": "subject",
    "fieldType": "text",
    "operator": "not_equals",
    "valueClass": "match",
    "expected": false,
    "conditionValue": "Refund",
    "ticketValue": "Refund"
  },
  {
    "id": "automation.matrix.not_equals.text.no_match",
    "field": "subject",
    "fieldType": "text",
    "operator": "not_equals",
    "valueClass": "no_match",
    "expected": true,
    "conditionValue": "Refund",
    "ticketValue": "Password reset instructions"
  },
  {
    "id": "automation.matrix.not_equals.text.null_value",
    "field": "subject",
    "fieldType": "text",
    "operator": "not_equals",
    "valueClass": "null_value",
    "expected": true,
    "conditionValue": "Refund",
    "ticketValue": "Password reset instructions"
  },
  {
    "id": "automation.matrix.not_equals.text.boundary",
    "field": "subject",
    "fieldType": "text",
    "operator": "not_equals",
    "valueClass": "boundary",
    "expected": true,
    "conditionValue": " Refund ",
    "ticketValue": "Refund"
  },
  {
    "id": "automation.matrix.not_equals.text.case_variant",
    "field": "subject",
    "fieldType": "text",
    "operator": "not_equals",
    "valueClass": "case_variant",
    "expected": true,
    "conditionValue": "REFUND",
    "caseSensitive": true,
    "ticketValue": "refund"
  },
  {
    "id": "automation.matrix.not_equals.select.match",
    "field": "priority",
    "fieldType": "select",
    "operator": "not_equals",
    "valueClass": "match",
    "expected": false,
    "conditionValue": "high",
    "ticketValue": "high"
  },
  {
    "id": "automation.matrix.not_equals.select.no_match",
    "field": "priority",
    "fieldType": "select",
    "operator": "not_equals",
    "valueClass": "no_match",
    "expected": true,
    "conditionValue": "urgent",
    "ticketValue": "low"
  },
  {
    "id": "automation.matrix.not_equals.select.null_value",
    "field": "priority",
    "fieldType": "select",
    "operator": "not_equals",
    "valueClass": "null_value",
    "expected": true,
    "conditionValue": "high"
  },
  {
    "id": "automation.matrix.not_equals.number.match",
    "field": "response_time",
    "fieldType": "number",
    "operator": "not_equals",
    "valueClass": "match",
    "expected": false,
    "ticketValue": 30,
    "conditionValue": 30
  },
  {
    "id": "automation.matrix.not_equals.number.no_match",
    "field": "response_time",
    "fieldType": "number",
    "operator": "not_equals",
    "valueClass": "no_match",
    "expected": true,
    "ticketValue": 30,
    "conditionValue": 999
  },
  {
    "id": "automation.matrix.not_equals.number.null_value",
    "field": "response_time",
    "fieldType": "number",
    "operator": "not_equals",
    "valueClass": "null_value",
    "expected": true,
    "conditionValue": 30
  },
  {
    "id": "automation.matrix.not_equals.number.boundary",
    "field": "response_time",
    "fieldType": "number",
    "operator": "not_equals",
    "valueClass": "boundary",
    "expected": false,
    "ticketValue": 30,
    "conditionValue": 30
  },
  {
    "id": "automation.matrix.not_equals.date.match",
    "field": "created_at",
    "fieldType": "date",
    "operator": "not_equals",
    "valueClass": "match",
    "expected": false,
    "ticketValue": "2026-09-21T06:33:03.225Z",
    "conditionValue": "2026-09-21T06:33:03.225Z"
  },
  {
    "id": "automation.matrix.not_equals.date.no_match",
    "field": "created_at",
    "fieldType": "date",
    "operator": "not_equals",
    "valueClass": "no_match",
    "expected": true,
    "ticketValue": "2026-09-21T06:33:03.225Z",
    "conditionValue": "2026-08-27T06:33:03.225Z"
  },
  {
    "id": "automation.matrix.not_equals.date.null_value",
    "field": "created_at",
    "fieldType": "date",
    "operator": "not_equals",
    "valueClass": "null_value",
    "expected": true,
    "conditionValue": "2026-09-21T06:33:03.225Z"
  },
  {
    "id": "automation.matrix.not_equals.date.boundary",
    "field": "created_at",
    "fieldType": "date",
    "operator": "not_equals",
    "valueClass": "boundary",
    "expected": false,
    "ticketValue": "2026-09-21T06:33:03.225Z",
    "conditionValue": "2026-09-21T06:33:03.225Z"
  },
  {
    "id": "automation.matrix.not_equals.boolean.match",
    "field": "is_urgent",
    "fieldType": "boolean",
    "operator": "not_equals",
    "valueClass": "match",
    "expected": false,
    "conditionValue": true,
    "ticketValue": true
  },
  {
    "id": "automation.matrix.not_equals.boolean.no_match",
    "field": "is_urgent",
    "fieldType": "boolean",
    "operator": "not_equals",
    "valueClass": "no_match",
    "expected": true,
    "conditionValue": true,
    "ticketValue": false
  },
  {
    "id": "automation.matrix.is_set.text.match",
    "field": "subject",
    "fieldType": "text",
    "operator": "is_set",
    "valueClass": "match",
    "expected": true,
    "ticketValue": "Refund requested"
  },
  {
    "id": "automation.matrix.is_set.text.null_value",
    "field": "subject",
    "fieldType": "text",
    "operator": "is_set",
    "valueClass": "null_value",
    "expected": false
  },
  {
    "id": "automation.matrix.is_set.select.match",
    "field": "priority",
    "fieldType": "select",
    "operator": "is_set",
    "valueClass": "match",
    "expected": true,
    "ticketValue": "high"
  },
  {
    "id": "automation.matrix.is_set.select.null_value",
    "field": "priority",
    "fieldType": "select",
    "operator": "is_set",
    "valueClass": "null_value",
    "expected": false
  },
  {
    "id": "automation.matrix.is_set.multiselect.match",
    "field": "tags",
    "fieldType": "multiselect",
    "operator": "is_set",
    "valueClass": "match",
    "expected": true,
    "ticketValue": [
      "vip"
    ]
  },
  {
    "id": "automation.matrix.is_set.multiselect.null_value",
    "field": "tags",
    "fieldType": "multiselect",
    "operator": "is_set",
    "valueClass": "null_value",
    "expected": false
  },
  {
    "id": "automation.matrix.is_set.number.match",
    "field": "response_time",
    "fieldType": "number",
    "operator": "is_set",
    "valueClass": "match",
    "expected": true,
    "ticketValue": 30
  },
  {
    "id": "automation.matrix.is_set.number.null_value",
    "field": "response_time",
    "fieldType": "number",
    "operator": "is_set",
    "valueClass": "null_value",
    "expected": false
  },
  {
    "id": "automation.matrix.is_set.date.match",
    "field": "created_at",
    "fieldType": "date",
    "operator": "is_set",
    "valueClass": "match",
    "expected": true,
    "ticketValue": "2026-09-26T06:33:03.225Z"
  },
  {
    "id": "automation.matrix.is_set.date.null_value",
    "field": "created_at",
    "fieldType": "date",
    "operator": "is_set",
    "valueClass": "null_value",
    "expected": false
  },
  {
    "id": "automation.matrix.is_set.boolean.match",
    "field": "is_urgent",
    "fieldType": "boolean",
    "operator": "is_set",
    "valueClass": "match",
    "expected": true,
    "ticketValue": true
  },
  {
    "id": "automation.matrix.is_set.boolean.null_value",
    "field": "is_urgent",
    "fieldType": "boolean",
    "operator": "is_set",
    "valueClass": "null_value",
    "expected": false
  },
  {
    "id": "automation.matrix.is_not_set.text.match",
    "field": "subject",
    "fieldType": "text",
    "operator": "is_not_set",
    "valueClass": "match",
    "expected": false,
    "ticketValue": "Refund requested"
  },
  {
    "id": "automation.matrix.is_not_set.text.null_value",
    "field": "subject",
    "fieldType": "text",
    "operator": "is_not_set",
    "valueClass": "null_value",
    "expected": true
  },
  {
    "id": "automation.matrix.is_not_set.select.match",
    "field": "priority",
    "fieldType": "select",
    "operator": "is_not_set",
    "valueClass": "match",
    "expected": false,
    "ticketValue": "high"
  },
  {
    "id": "automation.matrix.is_not_set.select.null_value",
    "field": "priority",
    "fieldType": "select",
    "operator": "is_not_set",
    "valueClass": "null_value",
    "expected": true
  },
  {
    "id": "automation.matrix.is_not_set.multiselect.match",
    "field": "tags",
    "fieldType": "multiselect",
    "operator": "is_not_set",
    "valueClass": "match",
    "expected": false,
    "ticketValue": [
      "vip"
    ]
  },
  {
    "id": "automation.matrix.is_not_set.multiselect.null_value",
    "field": "tags",
    "fieldType": "multiselect",
    "operator": "is_not_set",
    "valueClass": "null_value",
    "expected": true
  },
  {
    "id": "automation.matrix.is_not_set.number.match",
    "field": "response_time",
    "fieldType": "number",
    "operator": "is_not_set",
    "valueClass": "match",
    "expected": false,
    "ticketValue": 30
  },
  {
    "id": "automation.matrix.is_not_set.number.null_value",
    "field": "response_time",
    "fieldType": "number",
    "operator": "is_not_set",
    "valueClass": "null_value",
    "expected": true
  },
  {
    "id": "automation.matrix.is_not_set.date.match",
    "field": "created_at",
    "fieldType": "date",
    "operator": "is_not_set",
    "valueClass": "match",
    "expected": false,
    "ticketValue": "2026-09-26T06:33:03.225Z"
  },
  {
    "id": "automation.matrix.is_not_set.date.null_value",
    "field": "created_at",
    "fieldType": "date",
    "operator": "is_not_set",
    "valueClass": "null_value",
    "expected": true
  },
  {
    "id": "automation.matrix.is_not_set.boolean.match",
    "field": "is_urgent",
    "fieldType": "boolean",
    "operator": "is_not_set",
    "valueClass": "match",
    "expected": false,
    "ticketValue": true
  },
  {
    "id": "automation.matrix.is_not_set.boolean.null_value",
    "field": "is_urgent",
    "fieldType": "boolean",
    "operator": "is_not_set",
    "valueClass": "null_value",
    "expected": true
  },
  {
    "id": "automation.matrix.contains.text.match",
    "field": "subject",
    "fieldType": "text",
    "operator": "contains",
    "valueClass": "match",
    "expected": true,
    "conditionValue": "Refund",
    "ticketValue": "Order 123: Refund requested"
  },
  {
    "id": "automation.matrix.contains.text.no_match",
    "field": "subject",
    "fieldType": "text",
    "operator": "contains",
    "valueClass": "no_match",
    "expected": false,
    "conditionValue": "Refund",
    "ticketValue": "Password reset instructions"
  },
  {
    "id": "automation.matrix.contains.text.null_value",
    "field": "subject",
    "fieldType": "text",
    "operator": "contains",
    "valueClass": "null_value",
    "expected": false,
    "conditionValue": "Refund",
    "ticketValue": "Password reset instructions"
  },
  {
    "id": "automation.matrix.contains.text.boundary",
    "field": "subject",
    "fieldType": "text",
    "operator": "contains",
    "valueClass": "boundary",
    "expected": true,
    "conditionValue": "Refund",
    "ticketValue": "Refund at the very start"
  },
  {
    "id": "automation.matrix.contains.text.case_variant",
    "field": "subject",
    "fieldType": "text",
    "operator": "contains",
    "valueClass": "case_variant",
    "expected": false,
    "conditionValue": "REFUND",
    "caseSensitive": true,
    "ticketValue": "refund"
  },
  {
    "id": "automation.matrix.not_contains.text.match",
    "field": "subject",
    "fieldType": "text",
    "operator": "not_contains",
    "valueClass": "match",
    "expected": false,
    "conditionValue": "Refund",
    "ticketValue": "Order 123: Refund requested"
  },
  {
    "id": "automation.matrix.not_contains.text.no_match",
    "field": "subject",
    "fieldType": "text",
    "operator": "not_contains",
    "valueClass": "no_match",
    "expected": true,
    "conditionValue": "Refund",
    "ticketValue": "Password reset instructions"
  },
  {
    "id": "automation.matrix.not_contains.text.null_value",
    "field": "subject",
    "fieldType": "text",
    "operator": "not_contains",
    "valueClass": "null_value",
    "expected": true,
    "conditionValue": "Refund",
    "ticketValue": "Password reset instructions"
  },
  {
    "id": "automation.matrix.not_contains.text.boundary",
    "field": "subject",
    "fieldType": "text",
    "operator": "not_contains",
    "valueClass": "boundary",
    "expected": false,
    "conditionValue": "Refund",
    "ticketValue": "Refund at the very start"
  },
  {
    "id": "automation.matrix.not_contains.text.case_variant",
    "field": "subject",
    "fieldType": "text",
    "operator": "not_contains",
    "valueClass": "case_variant",
    "expected": true,
    "conditionValue": "REFUND",
    "caseSensitive": true,
    "ticketValue": "refund"
  },
  {
    "id": "automation.matrix.starts_with.text.match",
    "field": "subject",
    "fieldType": "text",
    "operator": "starts_with",
    "valueClass": "match",
    "expected": true,
    "conditionValue": "Refund",
    "ticketValue": "Refund order"
  },
  {
    "id": "automation.matrix.starts_with.text.no_match",
    "field": "subject",
    "fieldType": "text",
    "operator": "starts_with",
    "valueClass": "no_match",
    "expected": false,
    "conditionValue": "Refund",
    "ticketValue": "Password reset instructions"
  },
  {
    "id": "automation.matrix.starts_with.text.null_value",
    "field": "subject",
    "fieldType": "text",
    "operator": "starts_with",
    "valueClass": "null_value",
    "expected": false,
    "conditionValue": "Refund",
    "ticketValue": "Password reset instructions"
  },
  {
    "id": "automation.matrix.starts_with.text.boundary",
    "field": "subject",
    "fieldType": "text",
    "operator": "starts_with",
    "valueClass": "boundary",
    "expected": true,
    "conditionValue": "Refund",
    "ticketValue": "Refund order"
  },
  {
    "id": "automation.matrix.starts_with.text.case_variant",
    "field": "subject",
    "fieldType": "text",
    "operator": "starts_with",
    "valueClass": "case_variant",
    "expected": false,
    "conditionValue": "REFUND",
    "caseSensitive": true,
    "ticketValue": "refund"
  },
  {
    "id": "automation.matrix.ends_with.text.match",
    "field": "subject",
    "fieldType": "text",
    "operator": "ends_with",
    "valueClass": "match",
    "expected": true,
    "conditionValue": "Refund",
    "ticketValue": "order Refund"
  },
  {
    "id": "automation.matrix.ends_with.text.no_match",
    "field": "subject",
    "fieldType": "text",
    "operator": "ends_with",
    "valueClass": "no_match",
    "expected": false,
    "conditionValue": "Refund",
    "ticketValue": "Password reset instructions"
  },
  {
    "id": "automation.matrix.ends_with.text.null_value",
    "field": "subject",
    "fieldType": "text",
    "operator": "ends_with",
    "valueClass": "null_value",
    "expected": false,
    "conditionValue": "Refund",
    "ticketValue": "Password reset instructions"
  },
  {
    "id": "automation.matrix.ends_with.text.boundary",
    "field": "subject",
    "fieldType": "text",
    "operator": "ends_with",
    "valueClass": "boundary",
    "expected": true,
    "conditionValue": "Refund",
    "ticketValue": "order Refund"
  },
  {
    "id": "automation.matrix.ends_with.text.case_variant",
    "field": "subject",
    "fieldType": "text",
    "operator": "ends_with",
    "valueClass": "case_variant",
    "expected": false,
    "conditionValue": "REFUND",
    "caseSensitive": true,
    "ticketValue": "refund"
  },
  {
    "id": "automation.matrix.regex.text.match",
    "field": "subject",
    "fieldType": "text",
    "operator": "regex",
    "valueClass": "match",
    "expected": true,
    "conditionValue": "^Refund",
    "ticketValue": "Refund requested"
  },
  {
    "id": "automation.matrix.regex.text.no_match",
    "field": "subject",
    "fieldType": "text",
    "operator": "regex",
    "valueClass": "no_match",
    "expected": false,
    "conditionValue": "^Refund",
    "ticketValue": "Password reset instructions"
  },
  {
    "id": "automation.matrix.regex.text.null_value",
    "field": "subject",
    "fieldType": "text",
    "operator": "regex",
    "valueClass": "null_value",
    "expected": false,
    "conditionValue": "^Refund",
    "ticketValue": "Password reset instructions"
  },
  {
    "id": "automation.matrix.regex.text.boundary",
    "field": "subject",
    "fieldType": "text",
    "operator": "regex",
    "valueClass": "boundary",
    "expected": true,
    "conditionValue": "^Refund",
    "ticketValue": "Refund requested"
  },
  {
    "id": "automation.matrix.regex.text.case_variant",
    "field": "subject",
    "fieldType": "text",
    "operator": "regex",
    "valueClass": "case_variant",
    "expected": false,
    "conditionValue": "REFUND",
    "caseSensitive": true,
    "ticketValue": "refund"
  },
  {
    "id": "automation.matrix.has_one_of.multiselect.match",
    "field": "tags",
    "fieldType": "multiselect",
    "operator": "has_one_of",
    "valueClass": "match",
    "expected": true,
    "conditionValue": [
      "vip"
    ],
    "ticketValue": [
      "vip",
      "billing",
      "priority-support"
    ]
  },
  {
    "id": "automation.matrix.has_one_of.multiselect.no_match",
    "field": "tags",
    "fieldType": "multiselect",
    "operator": "has_one_of",
    "valueClass": "no_match",
    "expected": false,
    "conditionValue": [
      "vip"
    ],
    "ticketValue": [
      "general"
    ]
  },
  {
    "id": "automation.matrix.has_one_of.multiselect.null_value",
    "field": "tags",
    "fieldType": "multiselect",
    "operator": "has_one_of",
    "valueClass": "null_value",
    "expected": false,
    "conditionValue": [
      "vip"
    ]
  },
  {
    "id": "automation.matrix.has_none_of.multiselect.match",
    "field": "tags",
    "fieldType": "multiselect",
    "operator": "has_none_of",
    "valueClass": "match",
    "expected": false,
    "conditionValue": [
      "vip"
    ],
    "ticketValue": [
      "vip",
      "billing",
      "priority-support"
    ]
  },
  {
    "id": "automation.matrix.has_none_of.multiselect.no_match",
    "field": "tags",
    "fieldType": "multiselect",
    "operator": "has_none_of",
    "valueClass": "no_match",
    "expected": true,
    "conditionValue": [
      "vip"
    ],
    "ticketValue": [
      "general"
    ]
  },
  {
    "id": "automation.matrix.has_none_of.multiselect.null_value",
    "field": "tags",
    "fieldType": "multiselect",
    "operator": "has_none_of",
    "valueClass": "null_value",
    "expected": true,
    "conditionValue": [
      "vip"
    ]
  },
  {
    "id": "automation.matrix.has_all_of.multiselect.match",
    "field": "tags",
    "fieldType": "multiselect",
    "operator": "has_all_of",
    "valueClass": "match",
    "expected": true,
    "conditionValue": [
      "vip"
    ],
    "ticketValue": [
      "vip",
      "billing",
      "priority-support"
    ]
  },
  {
    "id": "automation.matrix.has_all_of.multiselect.no_match",
    "field": "tags",
    "fieldType": "multiselect",
    "operator": "has_all_of",
    "valueClass": "no_match",
    "expected": false,
    "conditionValue": [
      "vip"
    ],
    "ticketValue": [
      "general"
    ]
  },
  {
    "id": "automation.matrix.has_all_of.multiselect.null_value",
    "field": "tags",
    "fieldType": "multiselect",
    "operator": "has_all_of",
    "valueClass": "null_value",
    "expected": false,
    "conditionValue": [
      "vip"
    ]
  },
  {
    "id": "automation.matrix.greater_than.number.match",
    "field": "response_time",
    "fieldType": "number",
    "operator": "greater_than",
    "valueClass": "match",
    "expected": true,
    "ticketValue": 30,
    "conditionValue": 25
  },
  {
    "id": "automation.matrix.greater_than.number.no_match",
    "field": "response_time",
    "fieldType": "number",
    "operator": "greater_than",
    "valueClass": "no_match",
    "expected": false,
    "ticketValue": 30,
    "conditionValue": 35
  },
  {
    "id": "automation.matrix.greater_than.number.null_value",
    "field": "response_time",
    "fieldType": "number",
    "operator": "greater_than",
    "valueClass": "null_value",
    "expected": false,
    "conditionValue": 30
  },
  {
    "id": "automation.matrix.greater_than.number.boundary",
    "field": "response_time",
    "fieldType": "number",
    "operator": "greater_than",
    "valueClass": "boundary",
    "expected": false,
    "ticketValue": 30,
    "conditionValue": 30
  },
  {
    "id": "automation.matrix.greater_than.date.match",
    "field": "created_at",
    "fieldType": "date",
    "operator": "greater_than",
    "valueClass": "match",
    "expected": true,
    "ticketValue": "2026-09-21T06:33:03.225Z",
    "conditionValue": "2026-08-27T06:33:03.225Z"
  },
  {
    "id": "automation.matrix.greater_than.date.no_match",
    "field": "created_at",
    "fieldType": "date",
    "operator": "greater_than",
    "valueClass": "no_match",
    "expected": false,
    "ticketValue": "2026-09-21T06:33:03.225Z",
    "conditionValue": "2026-09-25T06:33:03.225Z"
  },
  {
    "id": "automation.matrix.greater_than.date.null_value",
    "field": "created_at",
    "fieldType": "date",
    "operator": "greater_than",
    "valueClass": "null_value",
    "expected": false,
    "conditionValue": "2026-09-21T06:33:03.225Z"
  },
  {
    "id": "automation.matrix.greater_than.date.boundary",
    "field": "created_at",
    "fieldType": "date",
    "operator": "greater_than",
    "valueClass": "boundary",
    "expected": false,
    "ticketValue": "2026-09-21T06:33:03.225Z",
    "conditionValue": "2026-09-21T06:33:03.225Z"
  },
  {
    "id": "automation.matrix.less_than.number.match",
    "field": "response_time",
    "fieldType": "number",
    "operator": "less_than",
    "valueClass": "match",
    "expected": true,
    "ticketValue": 30,
    "conditionValue": 35
  },
  {
    "id": "automation.matrix.less_than.number.no_match",
    "field": "response_time",
    "fieldType": "number",
    "operator": "less_than",
    "valueClass": "no_match",
    "expected": false,
    "ticketValue": 30,
    "conditionValue": 25
  },
  {
    "id": "automation.matrix.less_than.number.null_value",
    "field": "response_time",
    "fieldType": "number",
    "operator": "less_than",
    "valueClass": "null_value",
    "expected": false,
    "conditionValue": 30
  },
  {
    "id": "automation.matrix.less_than.number.boundary",
    "field": "response_time",
    "fieldType": "number",
    "operator": "less_than",
    "valueClass": "boundary",
    "expected": false,
    "ticketValue": 30,
    "conditionValue": 30
  },
  {
    "id": "automation.matrix.less_than.date.match",
    "field": "created_at",
    "fieldType": "date",
    "operator": "less_than",
    "valueClass": "match",
    "expected": true,
    "ticketValue": "2026-09-21T06:33:03.225Z",
    "conditionValue": "2026-09-25T06:33:03.225Z"
  },
  {
    "id": "automation.matrix.less_than.date.no_match",
    "field": "created_at",
    "fieldType": "date",
    "operator": "less_than",
    "valueClass": "no_match",
    "expected": false,
    "ticketValue": "2026-09-21T06:33:03.225Z",
    "conditionValue": "2026-08-27T06:33:03.225Z"
  },
  {
    "id": "automation.matrix.less_than.date.null_value",
    "field": "created_at",
    "fieldType": "date",
    "operator": "less_than",
    "valueClass": "null_value",
    "expected": false,
    "conditionValue": "2026-09-21T06:33:03.225Z"
  },
  {
    "id": "automation.matrix.less_than.date.boundary",
    "field": "created_at",
    "fieldType": "date",
    "operator": "less_than",
    "valueClass": "boundary",
    "expected": false,
    "ticketValue": "2026-09-21T06:33:03.225Z",
    "conditionValue": "2026-09-21T06:33:03.225Z"
  },
  {
    "id": "automation.matrix.greater_than_or_equal.number.match",
    "field": "response_time",
    "fieldType": "number",
    "operator": "greater_than_or_equal",
    "valueClass": "match",
    "expected": true,
    "ticketValue": 30,
    "conditionValue": 30
  },
  {
    "id": "automation.matrix.greater_than_or_equal.number.no_match",
    "field": "response_time",
    "fieldType": "number",
    "operator": "greater_than_or_equal",
    "valueClass": "no_match",
    "expected": false,
    "ticketValue": 30,
    "conditionValue": 35
  },
  {
    "id": "automation.matrix.greater_than_or_equal.number.null_value",
    "field": "response_time",
    "fieldType": "number",
    "operator": "greater_than_or_equal",
    "valueClass": "null_value",
    "expected": false,
    "conditionValue": 30
  },
  {
    "id": "automation.matrix.greater_than_or_equal.number.boundary",
    "field": "response_time",
    "fieldType": "number",
    "operator": "greater_than_or_equal",
    "valueClass": "boundary",
    "expected": true,
    "ticketValue": 30,
    "conditionValue": 30
  },
  {
    "id": "automation.matrix.greater_than_or_equal.date.match",
    "field": "created_at",
    "fieldType": "date",
    "operator": "greater_than_or_equal",
    "valueClass": "match",
    "expected": true,
    "ticketValue": "2026-09-21T06:33:03.225Z",
    "conditionValue": "2026-09-21T06:33:03.225Z"
  },
  {
    "id": "automation.matrix.greater_than_or_equal.date.no_match",
    "field": "created_at",
    "fieldType": "date",
    "operator": "greater_than_or_equal",
    "valueClass": "no_match",
    "expected": false,
    "ticketValue": "2026-09-21T06:33:03.225Z",
    "conditionValue": "2026-09-25T06:33:03.225Z"
  },
  {
    "id": "automation.matrix.greater_than_or_equal.date.null_value",
    "field": "created_at",
    "fieldType": "date",
    "operator": "greater_than_or_equal",
    "valueClass": "null_value",
    "expected": false,
    "conditionValue": "2026-09-21T06:33:03.225Z"
  },
  {
    "id": "automation.matrix.greater_than_or_equal.date.boundary",
    "field": "created_at",
    "fieldType": "date",
    "operator": "greater_than_or_equal",
    "valueClass": "boundary",
    "expected": true,
    "ticketValue": "2026-09-21T06:33:03.225Z",
    "conditionValue": "2026-09-21T06:33:03.225Z"
  },
  {
    "id": "automation.matrix.less_than_or_equal.number.match",
    "field": "response_time",
    "fieldType": "number",
    "operator": "less_than_or_equal",
    "valueClass": "match",
    "expected": true,
    "ticketValue": 30,
    "conditionValue": 30
  },
  {
    "id": "automation.matrix.less_than_or_equal.number.no_match",
    "field": "response_time",
    "fieldType": "number",
    "operator": "less_than_or_equal",
    "valueClass": "no_match",
    "expected": false,
    "ticketValue": 30,
    "conditionValue": 25
  },
  {
    "id": "automation.matrix.less_than_or_equal.number.null_value",
    "field": "response_time",
    "fieldType": "number",
    "operator": "less_than_or_equal",
    "valueClass": "null_value",
    "expected": false,
    "conditionValue": 30
  },
  {
    "id": "automation.matrix.less_than_or_equal.number.boundary",
    "field": "response_time",
    "fieldType": "number",
    "operator": "less_than_or_equal",
    "valueClass": "boundary",
    "expected": true,
    "ticketValue": 30,
    "conditionValue": 30
  },
  {
    "id": "automation.matrix.less_than_or_equal.date.match",
    "field": "created_at",
    "fieldType": "date",
    "operator": "less_than_or_equal",
    "valueClass": "match",
    "expected": true,
    "ticketValue": "2026-09-21T06:33:03.225Z",
    "conditionValue": "2026-09-21T06:33:03.225Z"
  },
  {
    "id": "automation.matrix.less_than_or_equal.date.no_match",
    "field": "created_at",
    "fieldType": "date",
    "operator": "less_than_or_equal",
    "valueClass": "no_match",
    "expected": false,
    "ticketValue": "2026-09-21T06:33:03.225Z",
    "conditionValue": "2026-08-27T06:33:03.225Z"
  },
  {
    "id": "automation.matrix.less_than_or_equal.date.null_value",
    "field": "created_at",
    "fieldType": "date",
    "operator": "less_than_or_equal",
    "valueClass": "null_value",
    "expected": false,
    "conditionValue": "2026-09-21T06:33:03.225Z"
  },
  {
    "id": "automation.matrix.less_than_or_equal.date.boundary",
    "field": "created_at",
    "fieldType": "date",
    "operator": "less_than_or_equal",
    "valueClass": "boundary",
    "expected": true,
    "ticketValue": "2026-09-21T06:33:03.225Z",
    "conditionValue": "2026-09-21T06:33:03.225Z"
  },
  {
    "id": "automation.matrix.between.number.match",
    "field": "response_time",
    "fieldType": "number",
    "operator": "between",
    "valueClass": "match",
    "expected": "probe",
    "ticketValue": 30,
    "conditionValue": [
      10,
      50
    ]
  },
  {
    "id": "automation.matrix.between.number.no_match",
    "field": "response_time",
    "fieldType": "number",
    "operator": "between",
    "valueClass": "no_match",
    "expected": "probe",
    "ticketValue": 30,
    "conditionValue": [
      10,
      50
    ]
  },
  {
    "id": "automation.matrix.between.number.null_value",
    "field": "response_time",
    "fieldType": "number",
    "operator": "between",
    "valueClass": "null_value",
    "expected": false,
    "conditionValue": 30
  },
  {
    "id": "automation.matrix.between.number.boundary",
    "field": "response_time",
    "fieldType": "number",
    "operator": "between",
    "valueClass": "boundary",
    "expected": "probe",
    "ticketValue": 30,
    "conditionValue": [
      10,
      50
    ]
  },
  {
    "id": "automation.matrix.between.date.match",
    "field": "created_at",
    "fieldType": "date",
    "operator": "between",
    "valueClass": "match",
    "expected": "probe",
    "ticketValue": "2026-09-21T06:33:03.225Z",
    "conditionValue": [
      "2026-09-16T06:33:03.225Z",
      "2026-09-25T06:33:03.225Z"
    ]
  },
  {
    "id": "automation.matrix.between.date.no_match",
    "field": "created_at",
    "fieldType": "date",
    "operator": "between",
    "valueClass": "no_match",
    "expected": "probe",
    "ticketValue": "2026-09-21T06:33:03.225Z",
    "conditionValue": [
      "2026-09-16T06:33:03.225Z",
      "2026-09-25T06:33:03.225Z"
    ]
  },
  {
    "id": "automation.matrix.between.date.null_value",
    "field": "created_at",
    "fieldType": "date",
    "operator": "between",
    "valueClass": "null_value",
    "expected": false,
    "conditionValue": "2026-09-21T06:33:03.225Z"
  },
  {
    "id": "automation.matrix.between.date.boundary",
    "field": "created_at",
    "fieldType": "date",
    "operator": "between",
    "valueClass": "boundary",
    "expected": "probe",
    "ticketValue": "2026-09-21T06:33:03.225Z",
    "conditionValue": [
      "2026-09-16T06:33:03.225Z",
      "2026-09-25T06:33:03.225Z"
    ]
  },
  {
    "id": "automation.matrix.is_within_last.date.match",
    "field": "created_at",
    "fieldType": "date",
    "operator": "is_within_last",
    "valueClass": "match",
    "expected": true,
    "conditionValue": "7 days",
    "ticketValue": "2026-09-26T06:33:03.225Z"
  },
  {
    "id": "automation.matrix.is_within_last.date.no_match",
    "field": "created_at",
    "fieldType": "date",
    "operator": "is_within_last",
    "valueClass": "no_match",
    "expected": false,
    "conditionValue": "1 hours",
    "ticketValue": "2026-09-26T04:33:03.225Z"
  },
  {
    "id": "automation.matrix.is_within_last.date.null_value",
    "field": "created_at",
    "fieldType": "date",
    "operator": "is_within_last",
    "valueClass": "null_value",
    "expected": false,
    "conditionValue": "7 days"
  },
  {
    "id": "automation.matrix.is_within_last.date.boundary",
    "field": "created_at",
    "fieldType": "date",
    "operator": "is_within_last",
    "valueClass": "boundary",
    "expected": true,
    "conditionValue": "7 days",
    "ticketValue": "2026-09-26T06:33:03.226Z"
  },
  {
    "id": "automation.matrix.is_today.date.match",
    "field": "created_at",
    "fieldType": "date",
    "operator": "is_today",
    "valueClass": "match",
    "expected": "probe",
    "ticketValue": "2026-09-26T06:33:03.226Z"
  },
  {
    "id": "automation.matrix.is_yesterday.date.match",
    "field": "created_at",
    "fieldType": "date",
    "operator": "is_yesterday",
    "valueClass": "match",
    "expected": "probe",
    "ticketValue": "2026-09-26T06:33:03.226Z"
  },
  {
    "id": "automation.matrix.is_this_week.date.match",
    "field": "created_at",
    "fieldType": "date",
    "operator": "is_this_week",
    "valueClass": "match",
    "expected": "probe",
    "ticketValue": "2026-09-26T06:33:03.226Z"
  },
  {
    "id": "automation.matrix.is_this_month.date.match",
    "field": "created_at",
    "fieldType": "date",
    "operator": "is_this_month",
    "valueClass": "match",
    "expected": "probe",
    "ticketValue": "2026-09-26T06:33:03.226Z"
  },
  {
    "id": "automation.matrix.is_true.boolean.match",
    "field": "is_urgent",
    "fieldType": "boolean",
    "operator": "is_true",
    "valueClass": "match",
    "expected": true,
    "ticketValue": true
  },
  {
    "id": "automation.matrix.is_false.boolean.match",
    "field": "is_urgent",
    "fieldType": "boolean",
    "operator": "is_false",
    "valueClass": "match",
    "expected": true,
    "ticketValue": false
  }
];


const suite = defineFeature("automation-operators", (s) => {
  for (const raw of CASES) {
    const c = raw as ConditionCase;
    if (c.id === "automation.matrix.seed") {
      s.behaviour(c.id, async (ctx) => {
        await runConditionCase(ctx, c); // seeds the probe rule on first use
      });
      continue;
    }
    s.behaviour(c.id, async (ctx) => {
      const { met, rejected } = await runConditionCase(ctx, c);
      if (c.expected !== "probe") {
        assert(!rejected, c.id + ": backend rejected a verified operator");
        assertEquals(
          met,
          c.expected as boolean,
          `${c.id}: ${c.operator} on ${c.fieldType} (${c.valueClass})`
        );
      }
    });
  }
});

export default suite;
