/**
 * Generates the automation coverage suites from the product catalog:
 *
 *  Layer 1 — features/automation-operators.feature.yaml
 *            EVERY operator × applicable field type × value class
 *            (match / no-match / null / boundary / case-variant), executed via
 *            POST /rules/:id/test in dry_run mode. Deterministic expectations
 *            are pinned; operators not verified in the backend run in probe
 *            mode (a boolean verdict must exist, actual value is reported).
 *
 *  Layer 2 — features/automation-pairwise.feature.yaml
 *            Pairwise (t=2) covering array across trigger × logic shape ×
 *            action type × field type.
 *
 * Run: npm run gen:matrix   (then `qa validate`)
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  ACTION_TYPES,
  FIELD_KEYS,
  LOGIC_SHAPES,
  OPERATORS,
  REPRESENTATIVE_TRIGGERS,
  buildConditionCase,
  type ActionType,
  type ConditionCase,
  type FieldType,
  type LogicShape,
  type ValueClass,
} from "../src/domain/automationCatalog.js";
import { pairwise } from "../src/domain/pairwise.js";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");

function valueClassesForPair(operator: string, fieldType: FieldType): ValueClass[] {
  const op = OPERATORS.find((o) => o.operator === operator)!;
  if (op.valueless) {
    return op.operator === "is_set" || op.operator === "is_not_set"
      ? ["match", "null_value"]
      : ["match"];
  }
  switch (fieldType) {
    case "text": return ["match", "no_match", "null_value", "boundary", "case_variant"];
    case "select":
    case "multiselect": return ["match", "no_match", "null_value"];
    case "boolean": return ["match", "no_match"];
    default: return ["match", "no_match", "null_value", "boundary"];
  }
}

const q = (s: unknown): string => JSON.stringify(String(s));

function manifest(
  featureId: string,
  title: string,
  behaviours: Array<{ id: string; description: string; spec: string }>
): string {
  const lines: string[] = [
    `id: ${featureId}`,
    `title: ${q(title)}`,
    "group: automation",
    "owner: qa-team@company.com",
    "severity: P1",
    "tags: [automation, regression, api, generated]",
    "dependsOn: [auth]",
    "layers: [api]",
    "environments: [local, ci, staging]",
    "",
    "behaviours:",
  ];
  for (const b of behaviours) {
    lines.push(
      `  - id: ${b.id}`,
      `    description: ${q(b.description)}`,
      `    spec: ${b.spec}`,
      `    testName: ${q(b.id)}`,
      "    severity: P1",
      "    layers: [api]"
    );
  }
  lines.push("", "data:", "  cleanup: true", "", "timeoutMs: 60000", "");
  return lines.join("\n");
}

function casesLiteral(varName: string, cases: unknown[]): string {
  return `const ${varName}: unknown[] = ${JSON.stringify(cases, null, 2)};\n`;
}

/** ---------- Layer 1: operator matrix ---------- */
const opCases: ConditionCase[] = [];
for (const op of OPERATORS) {
  for (const ft of op.fieldTypes) {
    for (const vc of valueClassesForPair(op.operator, ft)) {
      opCases.push(buildConditionCase(op.operator, ft, vc));
    }
  }
}
opCases.unshift({
  id: "automation.matrix.seed",
  field: "-",
  fieldType: "text",
  operator: "(seed)",
  valueClass: "match",
  expected: "probe",
});

const opsManifest = manifest(
  "automation-operators",
  "Automation operator matrix (generated)",
  opCases.map((c) => ({
    id: c.id,
    description: `${c.operator} on ${c.fieldType} (${c.valueClass}) → expect ${c.expected}`,
    spec: "specs/automation/automation.operators.spec.ts",
  }))
);

const opsSpec = `/**
 * GENERATED by scripts/generate-automation-matrix.ts — do not edit by hand.
 * Regenerate with: npm run gen:matrix
 */
import { defineFeature } from "../../src/orchestrator/suite.js";
import { assert, assertEquals } from "../../src/orchestrator/context.js";
import { runConditionCase } from "./automationHarness.js";
import type { ConditionCase } from "../../src/domain/automationCatalog.js";

${casesLiteral("CASES", opCases)}

const suite = defineFeature("automation-operators", (s) => {
  for (const raw of CASES) {
    const c = raw as ConditionCase;
    if (c.id === "automation.matrix.seed") {
      s.behaviour(c.id, async (ctx) => {
        await runConditionCase(ctx, c); // seeds the probe rule on first use
      });
      continue;
    }
    s.behaviour(c.id, async (ctx) => {
      const { met, rejected } = await runConditionCase(ctx, c);
      if (c.expected !== "probe") {
        assert(!rejected, c.id + ": backend rejected a verified operator");
        assertEquals(
          met,
          c.expected as boolean,
          \`\${c.id}: \${c.operator} on \${c.fieldType} (\${c.valueClass})\`
        );
      }
    });
  }
});

export default suite;
`;

/** ---------- Layer 2: pairwise rule space ---------- */
const fieldTypes = Object.keys(FIELD_KEYS) as FieldType[];
const rows = pairwise<string>([
  [...REPRESENTATIVE_TRIGGERS],
  [...LOGIC_SHAPES],
  [...ACTION_TYPES],
  fieldTypes,
]);

const pwCases = rows.map((r, i) => ({
  id: `automation.pairwise.${String(i + 1).padStart(3, "0")}`,
  trigger: r[0],
  logicShape: r[1] as LogicShape,
  actionType: r[2] as ActionType,
  fieldType: r[3] as FieldType,
}));

const pwManifest = manifest(
  "automation-pairwise",
  "Automation pairwise rule-space matrix (generated)",
  pwCases.map((c) => ({
    id: c.id,
    description: `${c.trigger} / ${c.logicShape} / ${c.actionType} / ${c.fieldType}`,
    spec: "specs/automation/automation.pairwise.spec.ts",
  }))
);

const pwSpec = `/**
 * GENERATED by scripts/generate-automation-matrix.ts — do not edit by hand.
 * Pairwise covering array: trigger × logic shape × action type × field type.
 */
import { defineFeature } from "../../src/orchestrator/suite.js";
import { ApiClient } from "../../src/api/http.js";
import { assert, assertEquals } from "../../src/orchestrator/context.js";
import { ACTION_TARGETS, FIELD_KEYS } from "../../src/domain/automationCatalog.js";
import type { LogicShape } from "../../src/domain/automationCatalog.js";
import {
  buildRulePayload,
  deriveConditionsMet,
  ensureProbeRule,
  extractActionResults,
} from "./automationHarness.js";

/** A guaranteed-match condition for any field type (is_set is backend-verified). */
const SAMPLE_VALUES: Record<string, unknown> = {
  text: "qa matrix",
  select: "high",
  multiselect: ["qa-matrix"],
  number: 1,
  date: new Date().toISOString(),
  boolean: true,
};

${casesLiteral("CASES", pwCases)}

type PwCase = {
  id: string;
  trigger: string;
  logicShape: LogicShape;
  actionType: keyof typeof ACTION_TARGETS;
  fieldType: keyof typeof FIELD_KEYS;
};

const suite = defineFeature("automation-pairwise", (s) => {
  for (const raw of CASES) {
    const c = raw as PwCase;
    s.behaviour(c.id, async (ctx) => {
      const ruleId = await ensureProbeRule(ctx);
      const api = ctx.api("AUTOMATION");
      const field = FIELD_KEYS[c.fieldType];
      const payload = buildRulePayload({
        name: \`qa-pw-\${c.id}\`,
        triggerType: String(c.trigger),
        logicShape: c.logicShape,
        condition: { field, operator: "is_set" },
        actionType: c.actionType,
        actionTarget: ACTION_TARGETS[c.actionType],
      });
      const testTicket: Record<string, unknown> = { [field]: SAMPLE_VALUES[c.fieldType] };
      const res = await api.post(\`/api/automation/rules/\${ruleId}/test\`, {
        test_ticket: testTicket,
        test_mode: "dry_run",
        rule_draft: payload,
      });
      assert(res.status < 500, \`testRule crashed (\${res.status}) for \${c.id}: \${JSON.stringify(res.data).slice(0, 300)}\`);
      assert(res.status < 400, \`testRule rejected \${c.id} (\${res.status}): \${JSON.stringify(res.data).slice(0, 300)}\`);
      const data = ApiClient.unwrap<Record<string, unknown>>(res);
      assertEquals(
        deriveConditionsMet(extractActionResults(data)),
        true,
        \`\${c.id}: guaranteed-match condition did not evaluate to true\`
      );
    });
  }
});

export default suite;
`;

writeFileSync(join(root, "features", "automation-operators.feature.yaml"), opsManifest);
mkdirSync(dirname(join(root, "specs", "automation", "automation.operators.spec.ts")), { recursive: true });
writeFileSync(join(root, "specs", "automation", "automation.operators.spec.ts"), opsSpec);
writeFileSync(join(root, "features", "automation-pairwise.feature.yaml"), pwManifest);
writeFileSync(join(root, "specs", "automation", "automation.pairwise.spec.ts"), pwSpec);

console.log(`operators matrix : ${opCases.length} behaviours (exhaustive operator × field type × value class)`);
console.log(`pairwise matrix  : ${pwCases.length} behaviours (rows covering trigger×logic×action×field pairs)`);
console.log("generated: features/automation-*.feature.yaml + specs/automation/automation.*.spec.ts");


